SELECT p.ID, p.START_DATE, p.FINISH_DATE,
       SUM(w.SALARY * (DATEDIFF('MONTH', p.START_DATE, p.FINISH_DATE) + 1)) AS PROJECT_COST
FROM project p
         INNER JOIN project_worker pw ON p.ID = pw.PROJECT_ID
         INNER JOIN worker w ON pw.WORKER_ID = w.ID
GROUP BY p.ID, p.START_DATE, p.FINISH_DATE
ORDER BY PROJECT_COST DESC;