CREATE TABLE IF NOT EXISTS client (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL CHECK(LENGTH(name) >= 3)
);

CREATE TABLE IF NOT EXISTS planet (
    id VARCHAR(10) UNIQUE NOT NULL PRIMARY KEY CHECK(id REGEXP '^[A-Z]*$'),
    name VARCHAR(500) NOT NULL CHECK(LENGTH(name) >= 1)
);

CREATE TABLE IF NOT EXISTS ticket (
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    client_id INTEGER NOT NULL,
    from_planet_id VARCHAR(10) NOT NULL,
    to_planet_id VARCHAR(10) NOT NULL,
    FOREIGN KEY (client_id) REFERENCES client(id) ON DELETE CASCADE,
    FOREIGN KEY (from_planet_id) REFERENCES planet(id) ON DELETE CASCADE,
    FOREIGN KEY (to_planet_id) REFERENCES planet(id) ON DELETE CASCADE
);

